# seed data


himym = {

"Ted" => "Mosby",
"Marshall" => "Eriksen",
"Robin" => "Sherbatsky",
"Barney" => "Stinson",
"Lily" => "Aldrin"

}


easy = {

"1 + 1" => "2",
"2 + 4" => "6",
"5 + 1" => "6",
"6 + 4" => "10",
"7 + 1" => "8",
"8 + 1" => "9",
"23 + 1" => "24",
"4 + 8" => "12",
"2 + 8" => "10",
"46 + 4" => "50",

}

capitals = {
	
"Croatia" => "Zagreb",
"Armenia" => "Yerevan",
"Cameroon" => "Yaounde",
"Namibia" => "Windhoek",
"Netherlands Antilles" => "Willemstad",
"Cocos Islands" => "West Island",
"New Zealand" => "Wellington",
"United States" => "Washington, DC",
"Poland" => "Warsaw",
"Lithuania" => "Vilnius",
"Laos" => "Vientiane",
"Austria" => "Vienna",
"Seychelles" => "Victoria",
"Malta" => "Valletta",
"Liechtenstein" => "Vaduz",
"Mongolia" => "Ulaanbaatar",
"Tunisia" => "Tunis",
"Faroe Islands" => "Torshavn",
"Japan" => "Tokyo",
"Albania" => "Tirana",
"Bhutan" => "Thimphu",
"Anguilla" => "The Valley",
"Iran" => "Tehran",
"Honduras" => "Tegucigalpa",
"Kiribati" => "Tarawa",
"Estonia" => "Tallinn",
"Taiwan" => "Taipei",
"Fiji" => "Suva",
"Sweden" => "Stockholm",
"Bulgaria" => "Sofia",
"Singapore" => "Singapore",
"South Korea" => "Seoul",
"Bosnia and Herzegovina" => "Sarajevo",
"Sao Tome and Principe" => "Sao Tome",
"Dominican Republic" => "Santo Domingo",
"Chile" => "Santiago",
"Yemen" => "Sanaa",
"El Salvador" => "San Salvador",
"San Marino" => "San Marino",
"Puerto Rico" => "San Juan",
"Costa Rica" => "San Jose",
"Northern Mariana Islands" => "Saipan",
"Saint Pierre and Miquelon" => "Saint-Pierre",
"Reunion" => "Saint-Denis",
"Guernsey" => "Saint Peter Port",
"Antigua and Barbuda" => "Saint John's",
"Jersey" => "Saint Helier",
"Grenada" => "Saint George's",
"Dominica" => "Roseau",
"Italy" => "Rome",
"British Virgin Islands" => "Road Town",
"Saudi Arabia" => "Riyadh",
"Latvia" => "Riga",
"Iceland" => "Reykjavik",
"Morocco" => "Rabat",
"Ecuador" => "Quito",
"South Africa" => "Pretoria",
"Cape Verde" => "Praia",
"Czech Republic" => "Prague",
"Vanuatu" => "Port-Vila",
"Trinidad and Tobago" => "Port-of-Spain",
"Haiti" => "Port-au-Prince",
"Papua New Guinea" => "Port Moresby",
"Mauritius" => "Port Louis",
"Montserrat" => "Plymouth",
"Cambodia" => "Phnom Penh",
"France" => "Paris",
"Suriname" => "Paramaribo",
"French Polynesia" => "Papeete",
"Panama" => "Panama",
"American Samoa" => "Pago Pago",
"North Korea" => "P'yongyang",
"Burkina Faso" => "Ouagadougou",
"Canada" => "Ottawa",
"Norway" => "Oslo",
"Aruba" => "Oranjestad",
"Greenland" => "Nuuk (Godthab)",
"Tonga" => "Nuku'alofa",
"New Caledonia" => "Noumea",
"Mauritania" => "Nouakchott",
"Western Sahara" => "none",
"Cyprus" => "Nicosia",
"Niger" => "Niamey",
"India" => "New Delhi",
"The Bahamas" => "Nassau",
"Kenya" => "Nairobi",
"Chad" => "N'Djamena",
"Oman" => "Muscat",
"Russia" => "Moscow",
"Comoros" => "Moroni",
"Uruguay" => "Montevideo",
"Liberia" => "Monrovia",
"Monaco" => "Monaco",
"Somalia" => "Mogadishu",
"Belarus" => "Minsk",
"Mexico" => "Mexico",
"Swaziland" => "Mbabane",
"Lesotho" => "Maseru",
"Mozambique" => "Maputo",
"Philippines" => "Manila",
"Bahrain" => "Manama",
"Nicaragua" => "Managua",
"Mayotte" => "Mamoutzou",
"Maldives" => "Male",
"Equatorial Guinea" => "Malabo",
"Marshall Islands" => "Majuro",
"Spain" => "Madrid",
"Luxembourg" => "Luxembourg",
"Zambia" => "Lusaka",
"Angola" => "Luanda",
"Svalbard" => "Longyearbyen",
"United Kingdom" => "London",
"Togo" => "Lome",
"Slovenia" => "Ljubljana",
"Portugal" => "Lisbon",
"Peru" => "Lima",
"Malawi" => "Lilongwe",
"Gabon" => "Libreville",
"Kuwait" => "Kuwait",
"Malaysia" => "Kuala Lumpur",
"Palau" => "Koror",
"Democratic Republic of the Congo" => "Kinshasa",
"Saint Vincent and the Grenadines" => "Kingstown",
"Norfolk Island" => "Kingston",
"Jamaica" => "Kingston",
"Rwanda" => "Kigali",
"Ukraine" => "Kiev",
"Sudan" => "Khartoum",
"Nepal" => "Kathmandu",
"Uganda" => "Kampala",
"Afghanistan" => "Kabul",
"Israel" => "Jerusalem",
"Saint Helena" => "Jamestown",
"Indonesia" => "Jakarta",
"Pakistan" => "Islamabad",
"Solomon Islands" => "Honiara",
"Finland" => "Helsinki",
"Cuba" => "Havana",
"Zimbabwe" => "Harare",
"Vietnam" => "Hanoi",
"Bermuda" => "Hamilton",
"Guam" => "Hagatna",
"Guatemala" => "Guatemala",
"Gibraltar" => "Gibraltar",
"Guyana" => "Georgetown",
"Cayman Islands" => "George Town",
"Botswana" => "Gaborone",
"Tuvalu" => "Funafuti",
"Sierra Leone" => "Freetown",
"Tajikistan" => "Dushanbe",
"Ireland" => "Dublin",
"Isle of Man" => "Douglas",
"Djibouti" => "Djibouti",
"Bangladesh" => "Dhaka",
"Tanzania" => "Dar es Salaam",
"Syria" => "Damascus",
"Senegal" => "Dakar",
"Denmark" => "Copenhagen",
"Guinea" => "Conakry",
"Sri Lanka" => "Colombo",
"Moldova" => "Chisinau",
"French Guiana" => "Cayenne",
"Saint Lucia" => "Castries",
"Venezuela" => "Caracas",
"Australia" => "Canberra",
"Egypt" => "Cairo",
"Burundi" => "Bujumbura",
"Argentina" => "Buenos Aires",
"Hungary" => "Budapest",
"Romania" => "Bucharest",
"Belgium" => "Brussels",
"Barbados" => "Bridgetown",
"Republic of the Congo" => "Brazzaville",
"Slovakia" => "Bratislava",
"Brazil" => "Brasilia",
"Columbia" => "Bogota",
"Guinea-Bissau" => "Bissau",
"Kyrgyzstan" => "Bishkek",
"Switzerland" => "Bern",
"Germany" => "Berlin",
"Belize" => "Belmopan",
"Yugoslavia" => "Belgrade",
"Lebanon" => "Beirut",
"China" => "Beijing",
"Saint Kitts and Nevis" => "Basseterre",
"Guadeloupe" => "Basse-Terre",
"The Gambia" => "Banjul",
"Central African Republic" => "Bangui",
"Thailand" => "Bangkok",
"Brunei" => "Bandar Seri Begawan",
"Mali" => "Bamako",
"Iraq" => "Baghdad",
"Cook Islands" => "Avarua",
"Greece" => "Athens",
"Paraguay" => "Asuncion",
"Kazakhstan" => "Astana",
"Turkmenistan" => "Ashgabat",
"Samoa" => "Apia",
"Madagascar" => "Antananarivo",
"Turkey" => "Ankara",
"Andorra" => "Andorra la Vella",
"Jordan" => "Amman",
"Niue" => "Alofi",
"Algeria" => "Algiers",
"Pitcairn Islands" => "Adamstown",
"Ghana" => "Accra",
"Nigeria" => "Abuja",
"United Arab Emirates" => "Abu Dhabi"
}

lyrics = {
"making love to you was never second best" => "melt with you",
"i've got to run away from the pain you drive into the heart of me" => "tainted love",
"so wild so free so far from me. you're all i want my fantasy" => "photograph",
"if you got the money honey we got your disease" => "welcome to the jungle",
"my baby may not be rich he's watchin every dime" => "let's hear it for the boy",
"take your-passion and make it happen" => "what a feeling",
"i think they got the alias that you been livin under" => "gloria",
"had a premonition that he shouldn't of gone alone" => "smugglers blues",
"and when the night is cold and dark you can't see you can't see light" => "never surrender",
"don't drink don't smoke what do ya do" => "goody two shoes",
"don't wanna be a girl like that do you wanna see a grown man cry" => "naughty naughty",
"strange voices are saying ah what did they say things. i can't understand" => "cruel summer",
"been workin so hard. i'm punchin my card" => "footloose",
"i know just how to whisper and i know just how to cry" => "makin love out of nothing at all",
"you got to roll with the punches to get to what's real" => "jump",
"just a look at that girl with the lights comin up in her eyes" => "somebody's baby",
"it's gonna take a lot to drag me away from you it's nothing that a hundred men or more could ever do" => "africa",
"and heart to heart you win if ya survive" => "the warrior",
"play the guitar on the mtv" => "money for nothing",
"tin roof.. rusted" => "love shack",
"you're givin me the chills baby please baby don't" => "mickey",
"i knew he must a been about seventeen" => "i love rock and roll",
"with the touch of a velvet glove" => "abracadabra",
"it's just another sunday in a tired old street" => "we built this city",
"slight of hand and a twist of fate on a bed of nails she makes me wait" => "with or without you",
"she's so fine she's all mine the girl is all right" => "legs",
"and your friends don't dance and if they don't dance well they're no friends of mine" => "safety dance",
"your feet are going to be on the ground your head is there to move you around" => "stand",
"oceans apart day after day and i slowly go insane" => "right here waiting for you",
"guess i should a known by the way you parked your car sideways that it wouldn't last" => "little red corvette",
"you're all the things i've got to remember" => "take on me",
"i need some company a guardian angel to keep me warm when the cold winds blow" => "take me home tonight",
"your very first kiss was your first kiss goodbye" => "you give love a bad name",
"so many times it happens too fast you trade your passion for glory" => "eye of the tiger",
"nations go to war over women like you it's just a form of appreciation" => "strut",
"i got a picture of you- ahh-ha-ahh-ha-ah-ah woh-oh-woh-oh" => "back on the chain gang",
"i i was standing you were there" => "never tear us apart",
"every claim you stake i'll be watching you" => "every breath you take",
"shoot me like a rocket into space" => "lovin every minute of it",
"this is the world we live in and these are the hands were given" => "land of confusion",
"don't wish it away don't look at it like this forever" => "i guess that's why they call it the blues",
"and even though i wander i'm keepin you in sight you're a candle in the wind on a cold dark winters night" => "can't fight this feeling",
"if you say goodbye to me tonight there will still be music left to write" => "longest time",
"oh yeah i just wanna watch the girls go by" => "summertime girls",
"i'll be alone dancin you know it baby" => "don't you forget about me",
"and you may say to yourself my god what have i done" => "once in a lifetime",
"scratches his head and does his best james dean" => "jack and diane",
"oh thinkin about all our younger years it was only you and me we were young and wild and free" => "heaven",
"like a knight in shining armor from a long time ago" => "glory of love",
"i've been meaning to tell you i've got this feeling that won't subside" => "hungry eyes",
"let the children's laughter remind us how we used to be" => "greatest love of all",
"i had a friend was a big baseball player back in high school" => "glory days",
"see yourself give your freewill a chance you've got to work to succeed" => "owner of a lonely heart",
"one likes to believe in the freedom of music" => "spirit of radio",
"heirs of the cold war tbat's what we've become. inherited troubles i'm mentally numb" => "crazy train",
"kid can't read at seventeen the words he knows are all obscene but it's all right" => "touch of grey",
"i never believed in things that i couldn't see i said if i can feel it how could it be" => "you can do magic",
"don't take money don't take fame don't need no credit card to ride this train" => "power of love",
"put me in coach i'm ready to play today" => "centerfield",
"just like the white wing dove sings a song sounds like she's singing" => "edge of 17",
"so let's sink another drink cause it'll give me time to think" => "dancing with myself",
"i need fifty dollars to make you holler" => "wild thing",
"i said mom this shirt is plaid with a butterfly collar" => "parents just don't understand",
"now every time i go for the mailbox gotta hold myself down" => "walking on sunshine",
"can make it i know i can. you broke the boy in me but you won't break the man" => "st. elmo's fire",
"i've had the blues the reds and the pinks" => "love stinks",
"at night i wake up with the sheets soaking wet and a freight train running through the middle of my head" => "i'm on fire",
"i'm lying in the rain but i never wave bye bye but i try" => "modern love",
"don't want no captain crunch don't want no raisin bran" => "eat it",
"he turned to me as if to say hurry boy it's waiting there for you" => "africa",
"you're not naive you must be strong" => "too shy",
"darken the city night is a wire steam in the subway earth is afire" => "hungry like the wolf",
"she had the body of a venus lord imagine my surprise" => "dude looks like a lady",
"i can't help recalling how it felt to kiss and hold you tight" => "always something there to remind me",
"will you meet him on the main line or will you catch him on the rebound" => "gloria",
"watching every motion in this foolish lover's game" => "take my breath away",
"you make the sun shine brighter than doris day" => "wake me up before you go-go",
"loving would be easy if your colours were like my dream red gold and green" => "karma chameleon",
"they threw an american flag in our face" => "allentown",
"when i'm dancing close to her i can smell the chemicals" => "she blinded me with science",
"she told me to come but i was already there" => "you shook me all night long",
"streetlight people living just to find emotion" => "don't stop believin'",
"it belongs to them let's give it back" => "beds are burning",
"everything you do is quite angelicate" => "why can't i be you",
"rolling like thunder under the covers" => "that's why they call it the blues",
"i don't know what you expect staring into the tv set" => "burning down the house",
"my eyes dilate my lips go green" => "start me up",
"i touch you once i touch you twice" => "if you leave",
"to have you with me i would swim the seven seas" => "we'll be together tonight",
"crazy little woman in a one man show" => "pour some sugar on me",
"went the distance now i'm back on my feet" => "eye of the tiger",
"got in a little hometown jam so they put a rifle in my hand" => "born in the u.s.a.",
"there is freedom within there is freedom without" => "don't dream it's over",
"but whatever road you choose i'm right behind you win or lose" => "forever young",
"i need fifty dollars to make you holler" => "wild thing",
"so let's sink another drink cause it'll give me time to think" => "dancin' with myself",
"goddess on the mountain top" => "venus",
"couldn't see how much i missed you now i do" => "only in my dreams",
"they even bother my poor father cause he's down with me" => "it's tricky",
"where can i find a woman like that" => "jesse's girl",
"paul i think i told you i'm a lover not a fighter" => "the girl is mine",
"mine's an ordinary life working when it's daylight and sleeping when it's night" => "take me home",

}
     

what_is = {

"What is a wallaby" => "kangaroo",
"What is a war between parties of the same country" => "civil war",
"What is a water taxi" => "gondola",
"What is a wether" => "a castrated ram",
"What is a whale's penis called" => "dork",
"What is a wind with a speed of 74 miles or more" => "hurricane",
"What is a woolly bear" => "caterpillar",
"What is a word formed from the initials of other words" => "acronym",
"What is a young otter called" => "whelp",
"What is a young whale" => "calf",
"What is a zeppelin" => "dirigible",
"What is activated for freckles to appear" => "melanocytes",
"What is acute hasopharyngitis" => "a cold",
"What is alfred e neuman's motto" => "what, me worry?",
"What is alice cooper's real name" => "vincent furnier",
"What is all hallow's eve" => "halloween",
"What is an aceituna in english" => "olive",
"What is an octothorpe" => "pound or number symbol",
"What is an algonquin" => "moose",
"What is an angle greater than 180 degrees and less than 360 degrees" => "reflex",
"What is an angle greater than 90 degrees" => "obtuse",
"What is an angle less than 90 degrees" => "acute",
"What is an animal stuffer" => "taxidermist",
"What is an australian bandit also known as" => "bushranger",
"What is an eight sided polygon called" => "octagon",
"What is an elver" => "baby eel",
"What is an enclosed car hung from a cable at a ski slope" => "gondola",
"What is an enlargement of the thyroid" => "goitre",
"What is an erythrocyte" => "red blood cell",
"What is an ethnologue" => "catalogue of languages",
"What is an example of a totally untraceable poison" => "acetylcholine",
"What is an extract of fermented and dried orchid pods" => "vanilla",
"What is an ideo locator" => "you are here marker",
"What is an integer that is greater than 1 and divisible only by itself and 1" => "prime number",
"What is an object worn as a charm" => "amulet",
"What is an ogee curve" => "s-curve",
"What is an olive in spanish" => "aceituna",
"What is an s-curve" => "ogee curve",
"What is anaemia" => "iron deficiency",
"What is another name for a football" => "pigskin",
"What is another name for a pigskin" => "football",
"What is another name for crude oil" => "black gold",
"What is another name for the carambula" => "star fruit",
"What is another name for the card game 'blackjack'" => "twenty one",
"What is another name for the card game 'twenty one'" => "blackjack",
"What is another name for the coyote" => "prairie wolf",
"What is another name for the prairie wolf" => "coyote",
"What is another name for the star fruit" => "carambula",
"What is apache indian corn beer" => "tizwin",
"What is armagnac" => "brandy",
"What is athens old quarter" => "plaka",
"What is attribution of divine honours on persons (living or dead) called" => "apotheosis",
"What is barbi's full name" => "barbara millicent roberts",
"What is basmati" => "rice",
"What is bed-wetting" => "enuresis",
"What is between panama and nicaragua" => "costa rica",
"What is black gold" => "crude oil",
"What is blackpool in irish" => "dubh linn",
"What is borscht" => "soup",
"What is bovine spongiform encephalopathy" => "mad cow disease",
"What is brady's profession" => "singer",
"What is brimstone" => "sulphur",
"What is ccdos" => "chinese character disk operating system",
"What is cerumen" => "earwax",
"What is cher's maiden name" => "sarkassian",
"What is china's sorrow" => "yellow river",
"What is considered history's greatest military evacuation" => "dunkirk",
"What is consumption" => "tuberculosis",
"What is conway twitty's real name" => "harold lloyd jenkins",
"What is cornelius mcgillicuddy's stage name" => "connie mack",
"What is cuneiform" => "writing system",
"What is dendrochronology" => "tree ring dating",
"What is dennis the menace's surname" => "mitchell",
"What is dick turpin's horse's name" => "black bess",
"What is dirty harry's surname" => "callahan",
"What is divination by means of lines and figures drawn in the earth" => "geomancy",
"What is dram" => "dynamic random access memory",
"What is drawing wild but politically favorable electoral districts" => "gerrymandering",
"What is e.t famous for saying" => "e.t phone home",
"What is earwax" => "cerumen",
"What is elton john's real name" => "reginald dwight",
"What is enuresis" => "bed-wetting",
"What is epidaurus famous for" => "greek theatre",
"What is evonne cawley's maiden name" => "evonne goolagong",
"What is exalting one's country above all others" => "nationalism",
"What is french national anthem" => "marseillaise",
"What is country is furthest from the equator" => "transylvania",
"What is green in a pure molten form" => "gold",
"What is growing plants in liquids rather than soil" => "hydroponics",
"What is haggis" => "sheep stomach",
"What is halloween" => "all hallow's eve",
"What is having a hole drilled through the cranium supposedly enabling people to reach a higher state of consciousness" => "trepanning",
"What is histology" => "study of tissues",
"What is hulk hogan's real name" => "terry bollea",
"What is hypertext markup language" => "html",
"What is improved if you sleep on your right side" => "digestion",
"What is in apple pips" => "cyanide",
"What is installed in the world's deepest mine in carletonville" => "refrigeration",
"What is interpol" => "international criminal police",
"What is is group of kangaroos" => "troop",
"What is it when five or fewer water molecules bond tightly together in a ring" => "cluster",
"What is jamaica's nickname" => "regaa boyz",
"What is jimmy carter's middle name" => "earl",
"What is john robertson osbourne's stage name" => "ozzy osbourne",
"What is john wayne's real name" => "marion morrison",
"What is kaolin" => "pure china clay",
"What is kermit d frog's girlfriend's name" => "miss piggy",
"What is known as 'the father of waters'" => "mississippi river",
"What is known as amundsen scott station" => "south pole",
"What is linda mccartney's maiden name" => "eastman",
"What is liquid clay used in pottery" => "slip",
"What is liquor distilled from the fermented mash of cereal grains and containing about 40 to 50 percent ethyl alcohol by volume" => "whiskey",
"What is made from the bark of the cinchona tree" => "quinine",
"What is made of fermented grape juice" => "wine",
"What is maryland's state song" => "maryland my maryland",
"What is mauna kea" => "volcano",
"What is max in 'the grinch who stole christmas" => "dog",
"What is measured by a geiger counter" => "radioactivity",
"What is mickey mouse's dog's name" => "pluto",
"What is missing from a navel orange" => "seeds",
"What is missing from the venus de milo" => "arms",
"What is mixed with kahlua to make a black russian" => "vodka",
"What is more addictive than all illicit drugs except crack and heroin combined" => "cigarettes",
"What is more effective than caffeine for waking up in the morning" => "apples",
"What is new brunswicks highest point at 820 m" => "mount carleton",
"What is new york city's street of forgotten men" => "the bowery",
"What is on a 5000 acre landfill at the head of jamaica bay near new york city" => "john f kennedy airport",
"What is on the banks of the river jumna" => "taj mahal",
"What is opposition to the jewish race called" => "anti-semitism",
"What is ornamental work in silver or gold thread" => "filigree",
"What is paedology" => "study of soil",
"What is penicillin made of" => "cheese mould",
"What is podobromhidrosis" => "smelly feet",
"What is pogonophobia the fear of" => "beards",
"What is pure china clay" => "kaolin",
"What is quicksilver better known as" => "mercury",
"What is raku" => "japanese pottery",
"What is recorded with two beams of light" => "holograph",
"what is removed with an orchidectomy" => "testicle",
"What is salicyclic acid better known as" => "aspirin",
"What is sally ride's scientific calling" => "physics",
"What is saltimbocca" => "an italian dish of ham and veal",
"What is samian ware" => "fine pottery",
"What is schizophrenia" => "hallucinations and delusions",
"What is sclerotinite" => "fungal remains",
"What is sex on the internet called" => "cybersex",
"What is soccer star pele's real name" => "edson arantes do nascimento",
"What is sometimes added to softdrinks to make them sweeter" => "coal",
"What is spain's biggest source of income" => "tourism",
"What is stuffed with a sheep's carcass stuffed with chickens stuffed with fish stuffed with eggs" => "roast camel",
"What is sushi" => "raw fish",
"What is switching letters (e.g saying jag of flapan instead of flag of japan)" => "spoonerism",
"What is switzerland's official neutral name" => "helvetic confederation",
"What is tattooed on glen campbell's arm" => "dagger",
"What is the rathaus in frankfurt" => "city hall",
"What is the bishop's stone" => "amethyst",
"What is the cresta run" => "toboggan course",
"What is the d in dwight d eisenhower's name" => "david",
"What is the pound or number symbol on the telephone" => "octothorpe",
"What is the word used for multiple personality disorder" => "mpd",
"What is the x on a railroad crossing" => "crossbuck",
"What is the 100 year old safe in washington dc" => "centennial safe",
"What is the 13.5 ton chime on london's tower clock" => "big ben",
"What is the 1983 bryan adams album which features the hit cuts like a knife" => "cuts like a knife",
"What is the acronym for yet another hierarchical officious oracle" => "yahoo",
"What is the act of founding settlements abroad" => "colonisation",
"What is the ancient religious language of india" => "sanskrit",
"What is the applied science to the study of society" => "sociology",
"What is the area of water between alaska and russia" => "bering strait",
"What is the art of fighting with gloves on the hand" => "boxing",
"What is the art of tracing designs and making impressions of them" => "lithography",
"What is the astrological sign for death" => "pluto",
"What is the atomic mass of bromine" => "79.9",
"What is the atomic mass of molybdenum" => "95.94",
"What is the atomic mass of platinum" => "195.09",
"What is the atomic mass of sulphur" => "32.06",
"What is the atomic number for californium" => "ninety eight",
"What is the atomic number for palladium" => "forty six",
"What is the atomic number for thalium" => "eighty one",
"What is the atomic weight of arsenic" => "seventy five",
"What is the atomic weight of uranium" => "ninety two",
"What is the attribution of human attributes to a deity" => "anthropomorphism",
"What is the average lifespan of a major league baseball" => "five to seven",
"What is the average lifespan of a tastebud" => "ten days",
"What is the average speed of a running pig" => "7.5 mph",
"What is the ball on top of a flagpole called" => "truck",
"What is the banking system in the u.s known as" => "federal reserve system",
"What is the base twenty numbering system" => "vigesimal",
"What is the basic flavoring of kahlua" => "coffee",
"What is the best selling single artist ever" => "garth brooks",
"What is the biggest criterion for prospective astronauts" => "eyesight",
"What is the billionth digit of pi" => "nine",
"What is the binot-simon scale used to measure" => "intelligence",
"What is the birthplace (city) of the late john candy" => "toronto",
"What is the birthstone for august" => "peridot",
"What is the birthstone for may" => "emerald",
"What is the birthstone for september" => "sapphire",
"What is the board game where it pays to know your trivia" => "trivial pursuit",
"What is the bone at the end of the spine" => "coccyx",
"What is the boy scout motto" => "be prepared",
"What is the branch of medicine dealing with curing by operative procedures" => "surgery",
"What is the branch of theology which concerns itself with the grounds and defense of the christian faith" => "apologetics",
"What is the brightest asteroid" => "vesta",
"What is the bundestag" => "german parliament"

}

# create decks

capitals_deck = Deck.create(:name => 'Capitals')
lyrics_deck = Deck.create(:name => 'Lyrics')
what_is_deck = Deck.create(:name => 'What is')
easy_deck = Deck.create(:name => 'Easy')
himym_deck = Deck.create(:name => 'How I Met Your Mother')

#create cards

capitals.each do |t,d|
  Card.create(:term => t, :definition => d, :deck => capitals_deck)
end

lyrics.each do |t,d|
  Card.create(:term => t, :definition => d, :deck => lyrics_deck)
end

what_is.each do |t,d|
  Card.create(:term => t, :definition => d, :deck => what_is_deck)
end

easy.each do |t,d|
  Card.create(:term => t, :definition => d, :deck => easy_deck)
end

himym.each do |t,d|
  Card.create(:term => t, :definition => d, :deck => himym_deck)
end

# create users

# User.create(:email => 'ben@email.com', :password => 'benf')
# User.create(:email => 'hannah@email.com', :password => 'hannahw')
# User.create(:email => 'chrism@email.com', :password => 'chrism')
# User.create(:email => 'alex@email.com', :password => 'alexr')

# create rounds

# 20.times do |x|
#   Round.create(:user_id => [1,2,3,4].sample, :deck_id => [1,2,3].sample)
# end	

# 30.times do |x|
# 	Guess.create(:round_id => [1,2,3,4,5,6,7,8,9,10].sample, :card_id => [1,2,3,4,5,6,7,8,9,10].sample, :correct => [true,false].sample)
# end
